version: '3.5'
services:
  storeconfig:
    image: {{.Traefik}}
    command:
      - "storeconfig"
      - "--api"
      - "--logLevel=info"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.acmelogging=true"
      - "--acme.overridecertificates=true"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email={{.Email}}"
      - "--acme.domains={{.Domain}}"
      - "--acme.keytype=EC256"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.swarmMode"
      - "--docker.domain={{.Domain}}"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul.server:8500"
      - "--consul.prefix=traefik"
      - "--maxidleconnsperhost=0"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  traefik:
    external: true
