apiVersion: 1

deleteDatasources:
  - name: Prometheus
#- name: Elastic

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true

#- name: Elastic
#  type: elasticsearch
#  access: proxy
#  database: "[metrics-]YYYY.MM.DD"
#  url: http://elastic:9200
#  jsonData:
#    interval: Daily
#    timeField: "@timestamp"